#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  anon_sym_EQ = 3,
  anon_sym_DOT = 4,
  anon_sym_value = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_arg = 8,
  anon_sym_COMMA = 9,
  anon_sym_PIPE = 10,
  anon_sym_BSLASH = 11,
  anon_sym_COLON = 12,
  sym_integer = 13,
  anon_sym_SQUOTE = 14,
  sym_char = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_var = 18,
  anon_sym_TILDE = 19,
  anon_sym_CARET = 20,
  sym_source_file = 21,
  sym__expression = 22,
  sym__expression_statement = 23,
  sym__value = 24,
  sym_function_definition = 25,
  sym_function_call = 26,
  sym_parameter_list = 27,
  sym_parameter_call_list = 28,
  sym_argument = 29,
  sym_unnamed_argument = 30,
  sym_named_argument = 31,
  sym_literals = 32,
  sym_number = 33,
  sym_float = 34,
  sym_symbol = 35,
  sym_function_block = 36,
  sym_variable = 37,
  sym_variable_declaration = 38,
  sym_local_var = 39,
  sym_environment_var = 40,
  sym_return_statement = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_parameter_list_repeat1 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_value] = "value",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_arg] = "arg",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE] = "|",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_COLON] = ":",
  [sym_integer] = "integer",
  [anon_sym_SQUOTE] = "'",
  [sym_char] = "char",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_TILDE] = "~",
  [anon_sym_CARET] = "^",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym__expression_statement] = "_expression_statement",
  [sym__value] = "_value",
  [sym_function_definition] = "function_definition",
  [sym_function_call] = "function_call",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter_call_list] = "parameter_call_list",
  [sym_argument] = "argument",
  [sym_unnamed_argument] = "unnamed_argument",
  [sym_named_argument] = "named_argument",
  [sym_literals] = "literals",
  [sym_number] = "number",
  [sym_float] = "float",
  [sym_symbol] = "symbol",
  [sym_function_block] = "function_block",
  [sym_variable] = "variable",
  [sym_variable_declaration] = "variable_declaration",
  [sym_local_var] = "local_var",
  [sym_environment_var] = "environment_var",
  [sym_return_statement] = "return_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_value] = anon_sym_value,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_arg] = anon_sym_arg,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_integer] = sym_integer,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_char] = sym_char,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym__expression_statement] = sym__expression_statement,
  [sym__value] = sym__value,
  [sym_function_definition] = sym_function_definition,
  [sym_function_call] = sym_function_call,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter_call_list] = sym_parameter_call_list,
  [sym_argument] = sym_argument,
  [sym_unnamed_argument] = sym_unnamed_argument,
  [sym_named_argument] = sym_named_argument,
  [sym_literals] = sym_literals,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [sym_symbol] = sym_symbol,
  [sym_function_block] = sym_function_block,
  [sym_variable] = sym_variable,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_local_var] = sym_local_var,
  [sym_environment_var] = sym_environment_var,
  [sym_return_statement] = sym_return_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_value] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_arg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_call_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_unnamed_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_named_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_literals] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_function_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_local_var] = {
    .visible = true,
    .named = true,
  },
  [sym_environment_var] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '$') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(13);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(7);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == ';') ADVANCE(3);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '^') ADVANCE(19);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(9);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '~') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 181 ||
          (913 <= lookahead && lookahead <= 937) ||
          (945 <= lookahead && lookahead <= 969)) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == 181 ||
          (913 <= lookahead && lookahead <= 937) ||
          (945 <= lookahead && lookahead <= 969)) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'v') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'g') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_arg);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_value);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_value] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_arg] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(55),
    [sym__expression] = STATE(10),
    [sym__expression_statement] = STATE(53),
    [sym_function_definition] = STATE(53),
    [sym_function_call] = STATE(53),
    [sym_function_block] = STATE(53),
    [sym_variable] = STATE(45),
    [sym_variable_declaration] = STATE(53),
    [sym_local_var] = STATE(17),
    [sym_environment_var] = STATE(17),
    [sym_return_statement] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_var] = ACTIONS(7),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_CARET,
    ACTIONS(13), 1,
      anon_sym_arg,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_parameter_list,
    STATE(45), 1,
      sym_variable,
    STATE(12), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [44] = 13,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    STATE(26), 1,
      sym_float,
    STATE(40), 1,
      sym_argument,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [88] = 13,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(26), 1,
      sym_float,
    STATE(41), 1,
      sym_argument,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [132] = 13,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    STATE(4), 1,
      sym_argument,
    STATE(26), 1,
      sym_float,
    STATE(61), 1,
      sym_parameter_call_list,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [176] = 13,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SEMI,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    STATE(26), 1,
      sym_float,
    STATE(39), 1,
      sym_argument,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [220] = 9,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      anon_sym_var,
    ACTIONS(41), 1,
      anon_sym_TILDE,
    ACTIONS(44), 1,
      anon_sym_CARET,
    STATE(45), 1,
      sym_variable,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(7), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [256] = 13,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    STATE(4), 1,
      sym_argument,
    STATE(26), 1,
      sym_float,
    STATE(54), 1,
      sym_parameter_call_list,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [300] = 12,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(29), 1,
      anon_sym_var,
    STATE(26), 1,
      sym_float,
    STATE(38), 1,
      sym_argument,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(24), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(32), 2,
      sym_unnamed_argument,
      sym_named_argument,
  [341] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_CARET,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_variable,
    STATE(7), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [376] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_variable,
    STATE(13), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [411] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_CARET,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_variable,
    STATE(7), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [446] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(11), 1,
      anon_sym_CARET,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_variable,
    STATE(7), 2,
      sym__expression,
      aux_sym_source_file_repeat1,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(53), 6,
      sym__expression_statement,
      sym_function_definition,
      sym_function_call,
      sym_function_block,
      sym_variable_declaration,
      sym_return_statement,
  [481] = 11,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(53), 1,
      anon_sym_BSLASH,
    STATE(26), 1,
      sym_float,
    STATE(57), 1,
      sym_function_block,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(58), 3,
      sym__value,
      sym_literals,
      sym_variable,
  [519] = 9,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(53), 1,
      anon_sym_BSLASH,
    STATE(26), 1,
      sym_float,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(31), 2,
      sym_number,
      sym_symbol,
    STATE(63), 2,
      sym_literals,
      sym_variable,
  [550] = 9,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(53), 1,
      anon_sym_BSLASH,
    STATE(26), 1,
      sym_float,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(25), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
  [581] = 2,
    ACTIONS(55), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(57), 10,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [598] = 3,
    ACTIONS(59), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(63), 2,
      anon_sym_EQ,
      anon_sym_COLON,
    ACTIONS(61), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [617] = 2,
    ACTIONS(65), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(67), 10,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [634] = 2,
    ACTIONS(69), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(71), 10,
      anon_sym_SEMI,
      anon_sym_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [651] = 9,
    ACTIONS(7), 1,
      anon_sym_var,
    ACTIONS(9), 1,
      anon_sym_TILDE,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      anon_sym_SQUOTE,
    ACTIONS(53), 1,
      anon_sym_BSLASH,
    STATE(26), 1,
      sym_float,
    STATE(17), 2,
      sym_local_var,
      sym_environment_var,
    STATE(30), 2,
      sym_literals,
      sym_variable,
    STATE(31), 2,
      sym_number,
      sym_symbol,
  [682] = 3,
    ACTIONS(73), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(77), 2,
      anon_sym_EQ,
      anon_sym_COLON,
    ACTIONS(75), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [701] = 3,
    ACTIONS(83), 1,
      anon_sym_DOT,
    ACTIONS(79), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(81), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [719] = 2,
    ACTIONS(85), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(87), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [734] = 2,
    ACTIONS(89), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(91), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [749] = 2,
    ACTIONS(79), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(81), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [764] = 2,
    ACTIONS(93), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(95), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [779] = 2,
    ACTIONS(97), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(99), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [794] = 2,
    ACTIONS(101), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(103), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [809] = 2,
    ACTIONS(105), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(107), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [824] = 2,
    ACTIONS(109), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(111), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [839] = 2,
    ACTIONS(113), 2,
      anon_sym_var,
      sym_identifier,
    ACTIONS(115), 8,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_BSLASH,
      sym_integer,
      anon_sym_SQUOTE,
      anon_sym_TILDE,
  [854] = 1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_var,
      anon_sym_TILDE,
      anon_sym_CARET,
  [863] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(119), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [875] = 1,
    ACTIONS(124), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_var,
      anon_sym_TILDE,
      anon_sym_CARET,
  [883] = 1,
    ACTIONS(126), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_var,
      anon_sym_TILDE,
      anon_sym_CARET,
  [891] = 1,
    ACTIONS(128), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_var,
      anon_sym_TILDE,
      anon_sym_CARET,
  [899] = 1,
    ACTIONS(119), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [906] = 3,
    ACTIONS(130), 1,
      anon_sym_SEMI,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_parameter_list_repeat1,
  [916] = 3,
    ACTIONS(130), 1,
      anon_sym_PIPE,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_parameter_list_repeat1,
  [926] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_parameter_list_repeat1,
  [936] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_parameter_list_repeat1,
  [946] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_PIPE,
    STATE(34), 1,
      aux_sym_parameter_list_repeat1,
  [956] = 3,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      aux_sym_parameter_list_repeat1,
  [966] = 2,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(142), 1,
      anon_sym_DOT,
  [973] = 2,
    ACTIONS(144), 1,
      anon_sym_value,
    ACTIONS(146), 1,
      anon_sym_LPAREN,
  [980] = 1,
    ACTIONS(148), 1,
      anon_sym_SEMI,
  [984] = 1,
    ACTIONS(150), 1,
      sym_identifier,
  [988] = 1,
    ACTIONS(152), 1,
      sym_identifier,
  [992] = 1,
    ACTIONS(154), 1,
      anon_sym_SEMI,
  [996] = 1,
    ACTIONS(156), 1,
      sym_identifier,
  [1000] = 1,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
  [1004] = 1,
    ACTIONS(160), 1,
      anon_sym_SEMI,
  [1008] = 1,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
  [1012] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [1016] = 1,
    ACTIONS(166), 1,
      sym_identifier,
  [1020] = 1,
    ACTIONS(168), 1,
      anon_sym_SEMI,
  [1024] = 1,
    ACTIONS(170), 1,
      anon_sym_SEMI,
  [1028] = 1,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
  [1032] = 1,
    ACTIONS(174), 1,
      sym_integer,
  [1036] = 1,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
  [1040] = 1,
    ACTIONS(178), 1,
      anon_sym_SEMI,
  [1044] = 1,
    ACTIONS(180), 1,
      anon_sym_SEMI,
  [1048] = 1,
    ACTIONS(182), 1,
      anon_sym_SEMI,
  [1052] = 1,
    ACTIONS(184), 1,
      anon_sym_SEMI,
  [1056] = 1,
    ACTIONS(186), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 132,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 256,
  [SMALL_STATE(9)] = 300,
  [SMALL_STATE(10)] = 341,
  [SMALL_STATE(11)] = 376,
  [SMALL_STATE(12)] = 411,
  [SMALL_STATE(13)] = 446,
  [SMALL_STATE(14)] = 481,
  [SMALL_STATE(15)] = 519,
  [SMALL_STATE(16)] = 550,
  [SMALL_STATE(17)] = 581,
  [SMALL_STATE(18)] = 598,
  [SMALL_STATE(19)] = 617,
  [SMALL_STATE(20)] = 634,
  [SMALL_STATE(21)] = 651,
  [SMALL_STATE(22)] = 682,
  [SMALL_STATE(23)] = 701,
  [SMALL_STATE(24)] = 719,
  [SMALL_STATE(25)] = 734,
  [SMALL_STATE(26)] = 749,
  [SMALL_STATE(27)] = 764,
  [SMALL_STATE(28)] = 779,
  [SMALL_STATE(29)] = 794,
  [SMALL_STATE(30)] = 809,
  [SMALL_STATE(31)] = 824,
  [SMALL_STATE(32)] = 839,
  [SMALL_STATE(33)] = 854,
  [SMALL_STATE(34)] = 863,
  [SMALL_STATE(35)] = 875,
  [SMALL_STATE(36)] = 883,
  [SMALL_STATE(37)] = 891,
  [SMALL_STATE(38)] = 899,
  [SMALL_STATE(39)] = 906,
  [SMALL_STATE(40)] = 916,
  [SMALL_STATE(41)] = 926,
  [SMALL_STATE(42)] = 936,
  [SMALL_STATE(43)] = 946,
  [SMALL_STATE(44)] = 956,
  [SMALL_STATE(45)] = 966,
  [SMALL_STATE(46)] = 973,
  [SMALL_STATE(47)] = 980,
  [SMALL_STATE(48)] = 984,
  [SMALL_STATE(49)] = 988,
  [SMALL_STATE(50)] = 992,
  [SMALL_STATE(51)] = 996,
  [SMALL_STATE(52)] = 1000,
  [SMALL_STATE(53)] = 1004,
  [SMALL_STATE(54)] = 1008,
  [SMALL_STATE(55)] = 1012,
  [SMALL_STATE(56)] = 1016,
  [SMALL_STATE(57)] = 1020,
  [SMALL_STATE(58)] = 1024,
  [SMALL_STATE(59)] = 1028,
  [SMALL_STATE(60)] = 1032,
  [SMALL_STATE(61)] = 1036,
  [SMALL_STATE(62)] = 1040,
  [SMALL_STATE(63)] = 1044,
  [SMALL_STATE(64)] = 1048,
  [SMALL_STATE(65)] = 1052,
  [SMALL_STATE(66)] = 1056,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_call_list, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(66),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_argument, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_local_var, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_var, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_environment_var, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_environment_var, 2),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_argument, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unnamed_argument, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unnamed_argument, 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_argument, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_named_argument, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_argument, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literals, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literals, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(9),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_call_list, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_call_list, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [164] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_block, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_supercollider(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
